name: PRInfoSetter
on:
 pull_request:
   types: 
    - opened
jobs:
  add-pr-info:
    name: Set reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Set reviewers
        env:
          REVIEWERS: "[\\\"ktc-Ryomm\\\", \\\"Ryomm\\\"]" # 全レビュアー
        run: |
          reviewers=$(echo "${{ env.REVIEWERS }}" | jq '.-["${{ github.actor }}"]')
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{ \"reviewers\": $reviewers }" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
      - name: Set assignees
        run: 'curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{ \"assignees\": [\"${{ github.actor }}\"] }" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees'
